### PR TITLE
Fix pattern for masterPage creation

### LINKED ISSUE #15: Apply the new pattern to create MasterPage
A new pattern to create MasterPage was discussed in https://github.com/Starcounter/Guidelines/issues/23 and implemented for reference in https://github.com/StarcounterApps/Website/pull/106.

Please apply the same pattern in Cashier app, namely:

- rename the class `StandalonePage` to `MasterPage` (json, json.cs, html files)
- replace `Handle.GET("/cashier/standalone"` handler with a `GetSessionFromMaster` method

### PR DESCRIPTION
**Pull request by bouguila**
Fix #15
renamed standalone -> master
replaced standalone handler with getMasterFromSession method

### CODE REVIEW

**Comment by warpech** [comment]
Thanks, I will review

**Comment by warpech** [comment]
The project does not build for me. The error message:

```
"c:\www\Cashier\Cashier.sln" (default target) (1) ->
"c:\www\Cashier\src\Cashier\Cashier.csproj" (default target) (2) ->
(GenerateTypedJSONCode target) ->
  ViewModels\MasterPage.json.cs : json error : Could not find file 'c:\www\Cashier\src\Cashier\ViewModels\MasterPage.js
on'. [c:\www\Cashier\src\Cashier\Cashier.csproj]
```

File: src/Cashier/Api/MainHandlers.cs [hunk 1]
```diff
@@ -98,7 +79,24 @@ public void Register()
...
+            }
+
+            MasterPage master = Session.Current.Data as MasterPage;
+
+            if (master == null)
+            {
+                master = new MasterPage();
+                Session.Current.Data = master;
+            }
+            master.Html = "/Cashier/viewmodels/MasterPage.html";
```
Comment (warpech) [inline src/Cashier/Api/MainHandlers.cs]: This line is wrong here, because it sets the `Html` value at each handler execution, causing the following patch to be always sent to the client. That, in turn, causes the page to rerender.

2017-06-20 18_52_24-cashier

Proposed solution: Move `/Cashier/viewmodels/MasterPage.html` as the static value in `MasterPage.json`.

**Comment by bouguila** [comment]
@warpech  you're totally right, i'm going to fix that! thx

**Comment by warpech** [comment]
Ping @bouguila
